exclude = [
    ".git",
]

[commands.prettier-json]
type = "both"
cmd = ["npx", "-y", "--", "prettier"]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = "**/*.json"
ok_exit_codes = 0
