exclude = [
    ".git",
]

[commands.prettier-json]
type = "both"
cmd = ["prettier"]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = "**/*.json"
ok_exit_codes = 0

[commands.prettier-markdown]
type = "both"
cmd = ["prettier", "--prose-wrap", "always"]
lint-flags = ["--check"]
tidy-flags = ["--write"]
path-args = "absolute-file"
include = "**/*.md"
ok_exit_codes = 0

[commands.golangci-lint-fmt]
type = "both"
cmd = ["golangci-lint", "fmt"]
lint-flags = "--diff"
ok-exit-codes = 0
invoke = "once"
include = ["**/*.go"]

[commands.golangci-lint]
type = "both"
cmd = ["golangci-lint", "run"]
tidy-flags = ["--fix"]
ok-exit-codes = 0
ignore-stderr = ".*"
invoke = "once"
path-args = "dir"
include = ["**/*.go"]
