baseURL = "https://maxmind.github.io/MaxMind-DB/"
title = "MaxMind DB"
disableKinds = ["taxonomy"]

[markup.highlight]
  noClasses = true
  style = "github"

[[module.mounts]]
  source = "../MaxMind-DB-spec.md"
  target = "content/_index.md"
