name: precious

on:
  push:
  pull_request:

jobs:
  precious:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Install precious
        run: |
          curl -L https://github.com/houseabsolute/precious/releases/download/v0.10.1/precious-Linux-musl-x86_64.tar.gz | \
            tar -xz -C /usr/local/bin precious
      - name: Run precious lint
        run: precious lint --all
