name: precious

on:
  push:
  pull_request:

jobs:
  precious:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install precious
        run: |
          curl -L https://github.com/houseabsolute/precious/releases/download/v0.10.1/precious-Linux-musl-x86_64.tar.gz | \
            tar -xz -C /usr/local/bin precious
      - name: Run precious lint
        run: precious lint --all
